# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

pod 'GoogleMLKit/PoseDetection', '6.0.0'
pod 'GoogleMLKit/PoseDetectionAccurate', '6.0.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # If you want to use the base implementation:
  # Pods for Runner

  target 'RunnerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
